#!/usr/bin/env bash
# PDF Fire — sign the packages and build the download repository (run in a terminal).
#
# Input:  dist/*.deb and dist/*.rpm (scripts/make-deb.sh, scripts/make-rpm.sh)
# Output: repo/  - upload the whole folder to the web site (REPO_URL), e.g. by SFTP:
#     repo/pdf-fire-signing-key.asc     the public key (computers trust it once)
#     repo/pdf-fire.repo                the repository file for Fedora (dnf)
#     repo/pdf-fire.sources             the repository file for Ubuntu (apt)
#     repo/INSTALL.txt                  how to install on Ubuntu and on Fedora
#     repo/apt/...                      signed apt repository (InRelease, Release.gpg)
#     repo/rpm/...                      signed .rpm packages + signed repodata
#
# The passphrase of the key is asked once; it is never stored (a file in the private
# runtime folder, deleted at the end).
set -euo pipefail

HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
SRC="$(cd "$HERE/../../.." && pwd)"   # the source tree (this repository)
ROOT="${PDFFIRE_WORK_DIR:-$(dirname "$SRC")}"   # build/, deps/, dist/, repo/ (outside the repository)
export GNUPGHOME="${PDFFIRE_SIGNING_HOME:-$HOME/.local/share/pdf-fire-signing/gnupg}"
REPO_URL="${PDFFIRE_REPO_URL:-https://firehouse360.com/pdf-fire}"
FEDORA_IMAGE="${PDFFIRE_FEDORA_IMAGE:-registry.fedoraproject.org/fedora:44}"
DIST="${PDFFIRE_DIST_DIR:-$ROOT/dist}"
REPO="${PDFFIRE_REPO_DIR:-$ROOT/repo}"
KEYDIR="${PDFFIRE_SIGNING_DIR:-$ROOT/signing}"

FINGERPRINT="$(cat "$KEYDIR/pdf-fire-signing-key.fingerprint" 2>/dev/null || true)"
if [ -z "$FINGERPRINT" ] || ! gpg --list-secret-keys "$FINGERPRINT" >/dev/null 2>&1; then
    echo "No signing key - run scripts/signing/create-signing-key.sh first." >&2
    exit 1
fi

shopt -s nullglob
DEBS=("$DIST"/*.deb)
RPMS=("$DIST"/*.rpm)
if [ ${#DEBS[@]} -eq 0 ] && [ ${#RPMS[@]} -eq 0 ]; then
    echo "Nothing to sign in $DIST." >&2
    exit 1
fi

# The passphrase, once (a private file, removed on exit)
PASSFILE="$(mktemp "${XDG_RUNTIME_DIR:-/tmp}/pdffire-pass.XXXXXX")"
GNUPGCOPY=""
cleanup() { shred -u "$PASSFILE" 2>/dev/null || rm -f "$PASSFILE"; [ -n "$GNUPGCOPY" ] && rm -rf "$GNUPGCOPY"; }
trap cleanup EXIT
chmod 600 "$PASSFILE"
read -r -s -p "Passphrase of the PDF Fire signing key: " PASS; echo
printf '%s' "$PASS" > "$PASSFILE"; unset PASS
GPGSIGN=(gpg --batch --yes --pinentry-mode loopback --passphrase-file "$PASSFILE" --local-user "$FINGERPRINT")
# Check the passphrase before doing anything
echo test | "${GPGSIGN[@]}" --clearsign >/dev/null || { echo "Wrong passphrase." >&2; exit 1; }

rm -rf "$REPO"
mkdir -p "$REPO"
cp "$KEYDIR/pdf-fire-signing-key.asc" "$REPO/"

# Apache: static files only, and the bare folder (/pdf-fire/) goes to the download page
cat > "$REPO/.htaccess" <<'HTACCESS'
# PDF Fire download repository - static files only (generated by build-repository.sh)
Options -Indexes -ExecCGI
<FilesMatch "\.(ph(p[2-7]?|t|tml|ps|ar)|cgi|pl|py|sh)$">
    Require all denied
</FilesMatch>
RemoveHandler .php .phtml .php3 .php4 .php5 .php7 .phps .pht .phtm .phar

AddType application/vnd.debian.binary-package .deb
AddType application/x-rpm .rpm
AddType application/pgp-keys .asc
AddType text/plain .repo .sources .txt
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    # The repository metadata changes on every release - never serve it stale
    <FilesMatch "^(InRelease|Release|Release\.gpg|Packages(\.gz)?|repomd\.xml(\.asc)?)$">
        Header always set Cache-Control "no-cache"
    </FilesMatch>
</IfModule>

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
RewriteRule ^$ /tools/pdf-fire [R=302,L]
HTACCESS

# ---- Ubuntu / Debian: a signed apt repository -----------------------------------
if [ ${#DEBS[@]} -gt 0 ]; then
    POOL="$REPO/apt/pool/main/p/pdf-fire"
    BINARY="$REPO/apt/dists/stable/main/binary-amd64"
    mkdir -p "$POOL" "$BINARY"
    cp "${DEBS[@]}" "$POOL/"
    (cd "$REPO/apt" && dpkg-scanpackages --multiversion pool /dev/null > dists/stable/main/binary-amd64/Packages 2>/dev/null)
    gzip -9nk "$BINARY/Packages"

    python3 - "$REPO/apt/dists/stable" <<'PY'
import hashlib, os, sys, email.utils, time
base = sys.argv[1]
files = ["main/binary-amd64/Packages", "main/binary-amd64/Packages.gz"]
lines = ["Origin: PDF Fire", "Label: PDF Fire", "Suite: stable", "Codename: stable",
         "Date: " + email.utils.formatdate(time.time(), usegmt=True),
         "Architectures: amd64", "Components: main",
         "Description: PDF Fire - PDF editor (Prospect VFD)"]
for name, algorithm in (("MD5Sum", "md5"), ("SHA256", "sha256")):
    lines.append(name + ":")
    for f in files:
        data = open(os.path.join(base, f), "rb").read()
        lines.append(" %s %d %s" % (hashlib.new(algorithm, data).hexdigest(), len(data), f))
open(os.path.join(base, "Release"), "w").write("\n".join(lines) + "\n")
PY
    "${GPGSIGN[@]}" --clearsign -o "$REPO/apt/dists/stable/InRelease" "$REPO/apt/dists/stable/Release"
    "${GPGSIGN[@]}" --armor --detach-sign -o "$REPO/apt/dists/stable/Release.gpg" "$REPO/apt/dists/stable/Release"

    cat > "$REPO/pdf-fire.sources" <<SOURCES
Types: deb
URIs: $REPO_URL/apt
Suites: stable
Components: main
Architectures: amd64
Signed-By: /etc/apt/keyrings/pdf-fire.asc
SOURCES
fi

# ---- Fedora: signed .rpm packages and repodata (in a Fedora container) -----------
if [ ${#RPMS[@]} -gt 0 ]; then
    mkdir -p "$REPO/rpm/x86_64"
    cp "${RPMS[@]}" "$REPO/rpm/x86_64/"

    # The container gets a private copy of the key folder (its own gpg-agent)
    GNUPGCOPY="$(mktemp -d "${XDG_RUNTIME_DIR:-/tmp}/pdffire-gnupg.XXXXXX")"
    cp -r "$GNUPGHOME"/. "$GNUPGCOPY"/
    rm -f "$GNUPGCOPY"/S.* 2>/dev/null || true

    podman run --rm \
        -v "$REPO/rpm:/repo:Z" -v "$GNUPGCOPY:/gnupg:Z" -v "$PASSFILE:/pass:ro,Z" \
        -e GNUPGHOME=/gnupg "$FEDORA_IMAGE" bash -euc "
            dnf -q -y install rpm-sign createrepo_c gnupg2 >/dev/null
            rpmsign --define '_gpg_name $FINGERPRINT' \
                    --define '_gpg_sign_cmd_extra_args --batch --pinentry-mode loopback --passphrase-file /pass' \
                    --addsign /repo/x86_64/*.rpm
            createrepo_c -q /repo
            gpg --batch --yes --pinentry-mode loopback --passphrase-file /pass -u '$FINGERPRINT' \
                --armor --detach-sign -o /repo/repodata/repomd.xml.asc /repo/repodata/repomd.xml
        "

    cat > "$REPO/pdf-fire.repo" <<REPOFILE
[pdf-fire]
name=PDF Fire
baseurl=$REPO_URL/rpm
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=$REPO_URL/pdf-fire-signing-key.asc
REPOFILE
fi

# ---- Verification: the signatures are checked with the PUBLIC key only ------------
VERIFYHOME="$(mktemp -d)"
gpg --homedir "$VERIFYHOME" --quiet --import "$REPO/pdf-fire-signing-key.asc"
if [ -f "$REPO/apt/dists/stable/InRelease" ]; then
    gpg --homedir "$VERIFYHOME" --verify "$REPO/apt/dists/stable/InRelease" 2>&1 | grep -q "Good signature" && echo "apt repository: signature OK"
fi
if [ ${#RPMS[@]} -gt 0 ]; then
    podman run --rm -v "$REPO:/repo:Z" "$FEDORA_IMAGE" bash -euc "
        rpm --import /repo/pdf-fire-signing-key.asc
        rpm -K /repo/rpm/x86_64/*.rpm" && echo "rpm packages: signatures OK"
fi
rm -rf "$VERIFYHOME"

FPR_SPACED="$(echo "$FINGERPRINT" | sed 's/.\{4\}/& /g')"
cat > "$REPO/INSTALL.txt" <<INSTALL
PDF Fire - installation
=======================

The packages are signed with the PDF Fire signing key. Its fingerprint:
    $FPR_SPACED
Compare it with the one the department gives you, before you trust the key.

Ubuntu / Debian (once):
    sudo install -d /etc/apt/keyrings
    sudo curl -fsSLo /etc/apt/keyrings/pdf-fire.asc $REPO_URL/pdf-fire-signing-key.asc
    sudo curl -fsSLo /etc/apt/sources.list.d/pdf-fire.sources $REPO_URL/pdf-fire.sources
    sudo apt update && sudo apt install pdf-fire
  Updates then come with the normal system updates.

Fedora (once):
    sudo dnf config-manager addrepo --from-repofile=$REPO_URL/pdf-fire.repo
    sudo dnf install pdf-fire
  (dnf asks to trust the key - check the fingerprint above.) Updates come with dnf upgrade.

A single downloaded file, without the repository:
    Fedora:  sudo rpm --import $REPO_URL/pdf-fire-signing-key.asc
             sudo dnf install ./pdf-fire-*.rpm
    Ubuntu:  sudo apt install ./pdf-fire_*.deb
INSTALL

echo
echo "Repository ready: $REPO"
echo "Upload the whole folder to: $REPO_URL"
read -r -p "Press Enter to close this window. " _ || true
